nexus:
  image: sonatype/nexus3
  tag: latest
  service:
    type: ClusterIP
    port: 8081

  config:
    nexus.properties: |
      nexus.datastore.enabled=true
      nexus.datastore.type=jdbc
      nexus.datastore.jdbc.driver=org.postgresql.Driver
      nexus.datastore.jdbc.url=jdbc:postgresql://postgresql.nexus.svc.cluster.local:5432/nexusdb
      nexus.datastore.jdbc.username=nexus
      nexus.datastore.jdbc.password=nexus123

postgresql:
  image: postgres
  tag: latest
  service:
    type: ClusterIP
    port: 5432
  username: nexus
  password: nexus123
  database: nexusdb

storageClass: gp2
persistence:
  enabled: true
  size: 10Gi
