apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus
data:
  nexus.properties: |
    nexus.datastore.enabled=true
    nexus.datastore.type=jdbc
    nexus.datastore.jdbc.driver=org.postgresql.Driver
    nexus.datastore.jdbc.url=jdbc:postgresql://postgresql:5432/nexusdb
    nexus.datastore.jdbc.username=nexus
    nexus.datastore.jdbc.password=nexus123
