apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus
data:
  NEXUS_DB_HOST: "postgresql"
  NEXUS_DB_PORT: "5432"
  NEXUS_DB_USER: "nexus"
  NEXUS_DB_NAME: "nexusdb"

  nexus.properties: |
    nexus.datastore.enabled=true
    nexus.datastore.type=jdbc
    nexus.datastore.jdbc.driver=org.postgresql.Driver
    nexus.datastore.jdbc.url=jdbc:postgresql://$(NEXUS_DB_HOST):$(NEXUS_DB_PORT)/$(NEXUS_DB_NAME)
    nexus.datastore.jdbc.username=$(NEXUS_DB_USER)
    nexus.datastore.jdbc.password=$(NEXUS_DB_PASS)
