apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus-config
  namespace: nexus
data:
  NEXUS_DB_HOST: "postgresql"
  NEXUS_DB_PORT: "5432"
  NEXUS_DB_USER: "nexus"
  NEXUS_DB_NAME: "nexusdb"

  nexus.properties: |
    nexus.datastore.enabled=true
    nexus.datastore.type=jdbc
    nexus.datastore.jdbc.driver=org.postgresql.Driver
    nexus.datastore.jdbc.url=jdbc:postgresql://postgresql:5432/nexusdb
    nexus.datastore.jdbc.username=nexus
    nexus.datastore.jdbc.password=${NEXUS_DB_PASSWORD}
