apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      securityContext:
        fsGroup: 200  # Ensures the volume has the correct group permissions
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
          volumeMounts:
            - name: nexus-storage
              mountPath: /nexus-data
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: nexus-config
          env:
            - name: NEXUS_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: nexus-db-secret
                  key: NEXUS_DB_PASS
          volumeMounts:
            - name: nexus-storage
              mountPath: /nexus-data
            - name: nexus-config-volume
              mountPath: /nexus-data/etc/nexus.properties
              subPath: nexus.properties
      volumes:
        - name: nexus-storage
          persistentVolumeClaim:
            claimName: nexus-pvc
        - name: nexus-config-volume
          configMap:
            name: nexus-config
